name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        fixture:
          - valid
          - configuration-alias
    uses: ./.github/workflows/check.yml
    with:
      working_directory: ./test/${{ matrix.fixture }}
