name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  valid:
    uses: ./.github/workflows/check.yml
    with:
      working_directory: ./test/valid
  configuration-alias:
    uses: ./.github/workflows/check.yml
    with:
      working_directory: ./test/configuration-alias
